version: '3.1'
services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io
      - ADMIN_PASSWORD=super-secret
      - ADMIN_KEY=demo-key
      - ADMIN_KEY_MAXAGE=500
      - PLUGINS=remote_ip,reject,heartbeat,blackout,normalise,enhance, slackthread
    restart: always

  db:
    image: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always